management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # Corregido: "drive-class-name" a "driver-class-name"
    password: 12345678
    url: jdbc:mysql://localhost:3306/db_persona?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
      show-sql: true

  boot:  # Corregido: La propiedad "boot" parece estar en el lugar equivocado, ¿quizás quisiste ponerlo dentro de "spring"?
    admin:
      client:
        url: http://localhost:9000
  application:
    name: product-service

logging:
  file:
    name: product-service.log
    max-history: 20
    max-size: 20MB


 
